// tests/keyboard.test.tsx
import React from 'react';
import { act, fireEvent, render, screen, cleanup, waitFor } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import userEvent from '@testing-library/user-event';
import type { Bootstrap, Config } from '../src/types';
const mocks = vi.hoisted(() => ({ invoke: vi.fn(), handlers: new Map<string, (event: {payload: unknown}) => void>() }));
vi.mock('@tauri-apps/api/core', () => ({ isTauri: () => true, invoke: mocks.invoke }));
vi.mock('@tauri-apps/api/event', () => ({ listen: async (name: string, handler: (event: {payload: unknown}) => void) => { mocks.handlers.set(name, handler); return () => mocks.handlers.delete(name); } }));
import App from '../src/ui/App';
const config: Config = {schemaVersion:1,provider:'ollama',providers:Object.fromEntries(['ollama','openai','anthropic','google','libretranslate'].map(id => [id,{baseUrl:'http://localhost:11434',model:'test',allowRemote:false,allowInsecure:false}])) as Config['providers'],source:'pt-BR',target:'en-US',tone:'casual',formality:'informal',relationship:'auto',debounceMs:500,timeoutSecs:60,temperature:0.2,promptExtra:'',composeShortcut:'Ctrl+Alt+T',selectionShortcut:'Ctrl+Alt+S',repeatShortcut:'Ctrl+Alt+R',theme:'dark',autostart:false};
afterEach(() => { cleanup(); vi.clearAllMocks(); });
it('Enter blocks incomplete output; Shift+Enter adds newline; Escape only hides', async () => {
  const boot: Bootstrap = {compact:false,config,platform:'windows',warning:null,shortcutError:null,insertionAvailable:true,paused:false,capabilities:{styles:true,regionalVariants:true,streaming:false,protocol:'Ollama'}};
  mocks.invoke.mockImplementation(async (name: string) => name === 'bootstrap' ? boot : undefined);
  render(<App />);
  const editor = screen.getByLabelText('Seu texto') as HTMLTextAreaElement;
  await waitFor(() => expect(editor.disabled).toBe(false));
  const user = userEvent.setup();
  await user.type(editor,'rascunho');
  await user.keyboard('{Shift>}{Enter}{/Shift}');
  expect(editor.value).toContain('\n');
  fireEvent.keyDown(editor, {key:'Enter'});
  expect(mocks.invoke.mock.calls.some(([name]) => name === 'insert_translation')).toBe(false);
  fireEvent.keyDown(editor, {key:'Escape'});
  await waitFor(() => expect(mocks.invoke).toHaveBeenCalledWith('hide_overlay', undefined));
  expect(editor.value).toContain('rascunho');
  expect(mocks.invoke.mock.calls.some(([name]) => name === 'insert_translation')).toBe(false);
});
it('shortcut panel stays minimal, opens full settings and preserves the draft on return', async () => {
  const boot: Bootstrap = {compact:true,config,platform:'windows',warning:null,shortcutError:null,insertionAvailable:false,paused:false,capabilities:{styles:true,regionalVariants:true,streaming:false,protocol:'Ollama'}};
  mocks.invoke.mockImplementation(async (name: string) => { if (name === 'bootstrap') return {...boot}; if (name === 'open_settings') boot.compact=false; });
  render(<App />);
  await screen.findByLabelText('Painel rápido de tradução');
  expect(screen.queryByRole('navigation')).toBeNull();
  const editor = screen.getByLabelText('Seu texto') as HTMLTextAreaElement;
  await waitFor(() => expect(document.activeElement).toBe(editor));
  fireEvent.change(editor, {target:{value:'meu rascunho'}});
  fireEvent.keyDown(editor, {key:'Enter'});
  expect(mocks.invoke.mock.calls.some(([name]) => name === 'insert_translation')).toBe(false);
  fireEvent.click(screen.getByRole('button', {name:'Abrir configurações'}));
  await screen.findByRole('heading', {name:'Configurações'});
  expect(mocks.invoke).toHaveBeenCalledWith('open_settings', undefined);
  boot.compact=true;
  await act(async () => { mocks.handlers.get('compose')?.({payload:null}); });
  await screen.findByLabelText('Painel rápido de tradução');
  expect((screen.getByLabelText('Seu texto') as HTMLTextAreaElement).value).toBe('meu rascunho');
  fireEvent.keyDown(screen.getByLabelText('Seu texto'), {key:'Escape'});
  await waitFor(() => expect(mocks.invoke).toHaveBeenCalledWith('hide_overlay', undefined));
});
