// tests/session.test.ts
import { afterEach, describe, expect, it, vi } from 'vitest';
import { TranslationSession, type SessionApi } from '../src/session';
import type { TranslationResult } from '../src/types';
function setup() { const api: SessionApi = {translate: vi.fn(), cancel: vi.fn().mockResolvedValue(undefined), insert: vi.fn().mockResolvedValue(undefined)}; return {api, session: new TranslationSession(api)}; }
function result(id: number, text = 'translation'): TranslationResult { return {id,text,provider:'ollama',model:'test',elapsedMs:10,cached:false}; }
afterEach(() => vi.useRealTimers());
describe('translation confirmation safety', () => {
  it('debounces without translating empty input', async () => { vi.useFakeTimers(); const {api,session}=setup(); session.updateText(''); await vi.advanceTimersByTimeAsync(600); expect(api.translate).not.toHaveBeenCalled(); session.updateText('oi'); await vi.advanceTimersByTimeAsync(300); session.updateText('oi amigo'); expect(session.canInsert()).toBe(false); await vi.advanceTimersByTimeAsync(500); expect(api.translate).toHaveBeenCalledTimes(1); expect(api.translate).toHaveBeenCalledWith(expect.any(Number),'oi amigo'); });
  it('discards out-of-order responses and blocks insertion immediately on edit', async () => { const {api,session}=setup(); const pending: Array<(v: TranslationResult) => void> = []; const ids: number[]=[]; vi.mocked(api.translate).mockImplementation(id => { ids.push(id); return new Promise(resolve => pending.push(resolve)); }); session.updateText('old'); const first=session.run(); session.updateText('new'); const second=session.run(); pending[1](result(ids[1],'new translation')); await second; expect(session.canInsert()).toBe(true); pending[0](result(ids[0],'old translation')); await first; expect(session.snapshot().output).toBe('new translation'); session.updateText('newer'); expect(session.canInsert()).toBe(false); expect(await session.insert()).toBe(false); expect(api.insert).not.toHaveBeenCalled(); session.cancel(); });
  it('does not insert while request is incomplete or after escape', async () => { const {api,session}=setup(); vi.mocked(api.translate).mockReturnValue(new Promise(() => {})); session.updateText('draft'); void session.run(); await session.insert(); expect(api.insert).not.toHaveBeenCalled(); session.cancel(); expect(session.snapshot().text).toBe('draft'); expect(session.canInsert()).toBe(false); });
  it('preserves source/output on focus failure and never retries insertion', async () => { const {api,session}=setup(); vi.mocked(api.translate).mockImplementation(async id=>result(id)); vi.mocked(api.insert).mockRejectedValue('focus changed'); session.updateText('draft'); await session.run(); expect(await session.insert()).toBe(false); expect(session.snapshot().text).toBe('draft'); expect(session.snapshot().output).toBe('translation'); expect(session.canInsert()).toBe(false); await session.insert(); expect(api.insert).toHaveBeenCalledTimes(1); });
  it('inserts reviewed Unicode and multiline exactly once', async () => { const {api,session}=setup(); vi.mocked(api.translate).mockImplementation(async id=>result(id)); session.updateText('draft'); await session.run(); session.editOutput('ação 😊\nGPIO38'); await session.insert(); expect(api.insert).toHaveBeenCalledWith(expect.any(Number),'ação 😊\nGPIO38'); expect(session.snapshot().text).toBe(''); expect(api.insert).toHaveBeenCalledTimes(1); });
  it('repeating is memory-only and never auto-inserts', async () => { const {api,session}=setup(); vi.mocked(api.translate).mockImplementation(async id=>result(id)); session.updateText('draft'); await session.run(); session.repeat(); expect(api.insert).not.toHaveBeenCalled(); expect(session.snapshot().text).toBe('draft'); session.clear(); session.repeat(); expect(session.snapshot().text).toBe(''); });
});
